all:
#  - '.github/workflows/ci.yml'
#  - '.github/workflows/lima.yml'
#  - '.github/workflows/windows.yml'
#  - 'hack/**'
#  - 'Makefile'
#  - 'vendor/**'
#  - 'test/tools/**'
#  - 'test/registries*.conf'
#  - 'version/rawversion/*'
  - 'willnotmatch'

apiv2:
  - 'test/apiv2/**'
  - 'test/python/**'

bindings:
 - 'pkg/bindings/test/**'

docker_py:
 - 'test/python/**'

unit:
  - '**/*_test.go'

compose_v2:
  - 'test/compose/**'

int:
  - 'test/e2e/**'
  - 'test/utils/**'

sys:
  - 'test/system/**'

machine:
  - 'cmd/podman/machine/**'
  - 'pkg/machine/**'
  - '**/*machine*.go'

upgrade:
  - 'test/upgrade/**'
  - 'test/system/*.bash'

windows:
  - 'winmake.ps1'
  - 'hack/ci/win-*.ps1'
  - '.github/workflows/windows.yml'

installer:
  - 'contrib/win-installer/**'
